brokers/kafka.go, brokers/kafka_test.go, config.json, config/config.go, config_test.go, init.go, main.go
Implement Broker Backend interface for Messaging rest API
(pub/sub --> through rest --> to kafka broker network)
Implement a Kafka broker backend interface using sarama library 
This backend will exist behind a restAPI with restfull calls to Produce and Consume messages.
- Use sarama's SyncProducer to send message to a topic and close connection
- Since sarama's Consumer is Async and uses channels to consume data, a "sync" like Consume function is implemented. This function receives a topic and an offset (as input), checks topic's currentMaxOffset on broker and consumes all available messages till latest one and then closes the channel. The messages are returned as an array to the restAPI (as output)
- main function hosts temporarily a simple api frontend implementation with pub/sub calls …
=> ARGO-319 Broker Backend interface implementation

auth/auth_test.go, auth/users.go, brokers/kafka.go, brokers/mock.go, config.json, config/config.go, config/config.json, config/config_test.go, doc/swagger/swagger.yaml, handlers.go, handlers_test.go, routing.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go, stores/store_test.go, subscriptions/subscription.go, subscriptions/subscription_test.go, topics/topic.go, topics/topic_test.go
In each request a api key token is provided as url parameter (spec)
e.g. GET `/v1/project/PROJECT101/topics?key=T0K3N`
Authentication mechanism checks in store if the project/key combination corresponds to an existing
user. 
Authentication is performed through a WrapAuthentication wrapper that can be appended to handler chain on demand. A configuration parameter is used `use_authentication:true` to enable/disable the use of authentication on the API
After the user has been authenticated, there is an authorization process based on roles to see if the user has access to the resource. In the store there are entries in the roles collection like the following
```json
{ "resource": "topics:list", "roles": ["admin","reader","publisher"] }
```
After authentication the role list of a user is …
=> ARGO-375 Add Authentication to Messaging API

auth/auth_test.go, doc/swagger/swagger.yaml, handlers.go, handlers_test.go, routing.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go, topics/topic.go, topics/topic_test.go
Add Create topic request
The implementation of the request must adhere to the following signature
`PUT /v1/projects/PROJECT101/topic/TOPICNEW`
if succesfull must return a topic object response like the following
```json
{
"name": "/projects/PROJECT101/topics/TOPICNEW"
}
```
and `code 200`
if topic exists an appropriate errorMsg must be returned with `code 409 `
=> ARGO-376 Create topic request

doc/swagger/swagger.yaml, handlers.go, handlers_test.go, routing.go, subscriptions/subscription.go, subscriptions/subscription_test.go, topics/topic.go
Implement Create Subscription request
The implementation of the request must adhere to the following signature
`PUT /v1/projects/PROJECT101/subscriptions/SUBNEW`
Post Body:
```json
{
"topics":"/projects/PROJECT101/topics/TOPIC101"
}
```
if succesfull must return a topic object response like the following
```json
{
"name": "/projects/PROJECT101/subscriptions/SUBNEW",
"topic":"/projects/PROJECT101/project/TOPIC101"
}
```
and `code 200`
if topic exists an appropriate errorMsg must be returned with `code 409 `
=> ARGO 378- Create subscription request

doc/swagger/swagger.yaml, handlers.go, handlers_test.go, routing.go, subscriptions/subscription.go, subscriptions/subscription_test.go
Implement subscription delete Request. 
Request must adhere to the following signature:
` DELETE /v1/projects/PROJET101/subscriptions/SUB101`
- if deleleted return empty response and `CODE 200`
- if not deleted return ErrorMsg and appropriate `CODE`
=> ARGO-379 Implement Subscription Delete Request

auth/users.go, brokers/broker.go, brokers/kafka.go, brokers/mock.go, config.json, config/config.go, config/config.json, config/config_test.go, doc/swagger/swagger.yaml, handlers.go, handlers_test.go, main.go, messages/message.go, routing.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go, stores/store_test.go, subscriptions/subscription.go, subscriptions/subscription_test.go, validation.go
=> ARGO-398 Add Ack Request and Align Error Messages

config.json, config/config.go, config/config.json, config/config_test.go, doc/v1/docs/api_basic.md, main.go
Enforce HTTPS in ARGO Messaging API
=> ARGO-414 Enforce HTTPS

config.json, config/config.go, config/config.json, config/config_test.go, doc/v1/docs/api_basic.md, handlers.go, handlers_test.go, main.go, routing.go
Messaging API configuration maintained the following boolean flags:
`use_authentication`, `use_authorization` and `use_ack` to demonstrate flexibility on being able to enable/disable various mechanisms on the request handling chain. Since those features must be always enabled it is prefered to remove the configuration options and set the mechanisms always on
=> ARGO-437 Make Auth and Ack mechanisms mandatory

brokers/kafka.go, handlers_test.go, main.go, push/push.go, push/push_test.go, push/sender.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go, stores/store_test.go, subscriptions/subscription.go, subscriptions/subscription_test.go
Implement Push workers. Each push worker is a task responsible for running the following repeated activity:
- Check if the subscription's topic has new messages and consume them
- Send messages at a variable rate (slow-start) to the specified endpoint
Implement Push workers as go routines.
=> ARGO-436 Implement Push workers

brokers/mock.go, doc/swagger/swagger.yaml, doc/v1/docs/api_topics.md, examples/flask_receive_endpoint/receiver.py, handlers_test.go, messages/message.go, messages/message_test.go, push/push.go
Push Message response is slighty different from pull (needs to contain subscription information) like: 
```json
{
"message":{  },
"subscription":"foo"
}
```
from:
```json
"attributes": [{"key":"...","value":"..."},{"key2":"...","value2":"..."}]
to:
"attributes":{"key":"value","key2":"value2"}
```
=> ARGO-408 Receive Push Messages. Fix Msg Attributes

brokers/broker.go, brokers/kafka.go, brokers/mock.go, doc/swagger/swagger.yaml, handlers.go, push/push.go, stores/mongo.go
When handling subscriber pull requests allow the following:
- Keep the connection alive until messages are received
- Returned immediately (if parameter is set)
=> ARGO-424 In pull mode keep connection alive until msg retrieval

doc/swagger/swagger.yaml, doc/v1/docs/api_subs.md, handlers.go, handlers_test.go, push/push.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go, stores/store_test.go, subscriptions/subscription.go, subscriptions/subscription_test.go
Add support for configurable retry policy. If a user changes the retry policy restart the push subscription with the new policy at hand
eg:
```json
{
"name": "/projects/ARGO/subscriptions/sub1",
"topic": "/projects/ARGO/topics/topic1",
"pushConfig": {
"pushEndpoint": "example.foo",
"retryPolicy": {
"type": "linear",
"period": 300
}
},
"ackDeadlineSeconds": 10
}
```
=> ARGO-422 Support for configurable retry policy

brokers/kafka.go, handlers.go, push/push.go
=> ARGO-469 Lock Per topic. Stop pusher on subscription delete

handlers.go, push/push.go
Delete subscription caused a null pointer exception in pusher before stopping it
=> ARGO-490 Fix delete subscription bug

handlers.go, push/push.go
=> ARGO-490 Further fix of delete subscription bug

auth/users.go, doc/swagger/swagger.yaml, doc/v1/docs/api_subs.md, doc/v1/docs/auth.md, handlers.go, handlers_test.go, routing.go, stores/mock.go, stores/mongo.go, stores/store.go, subscriptions/subscription.go, subscriptions/subscription_test.go, topics/topic.go, topics/topic_test.go
Implement requests to list and edit acls on resources (topics/subscriptions)
=> ARGO-468 Allow admins to list and modify acls

push/sender.go
Should accept http status code = 102 as valid ack (instead of 101)
=> ARGO-472 Fix push ack http status code from 101 to 102

doc/swagger/swagger.yaml
Fix swagger definition for modifyAcl from 'get' to 'post'
=> ARGO-468 Fix swagger modifyAcl from get to post

handlers.go
In some cases API returns a concat list of json errors such as :
```
error {
}
error {
}
```
which is not valid json. This happends because after some ErrorResponse handling statements, the return directive was ommited, so the handler continued working ahead, even though a response was ready to be immediately served. This resulted in pilling error json strings in the response Body
=> ARGO-495 Handlers: Fix to return immediately after responding Error

auth/auth_test.go, auth/users.go, doc/v1/docs/auth.md, handlers.go, handlers_test.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go, topics/topic.go
ARGO-506 Check user existence before modifying sub ACL
When modifying an ACL, the list must not contain users that are non-existent
The response in the case of a modACL with non valid users:
`404 NOT_FOUND`
```
{
"error": {
"code": 404,
"message": "User(s): UserFoo1,UserFoo2 do not exist",
"status": "NOT_FOUND"
}
}
```
=> ARGO-505 Check user existence before modifying topic ACL

subscriptions/subscription.go, subscriptions/subscription_test.go, topics/topic.go, topics/topic_test.go
When removing all users from a topic, or a subscription the response returns null value. The response should return an empty array such as 
```
{ "authorized_users" : [] }
```
=> ARGO-507 Fix acl null value response

brokers/broker.go, brokers/kafka.go, brokers/mock.go, doc/v1/docs/api_errors.md, handlers.go
When message size exceeds kafka allowed size API service breaks and closes connection. Instead it should return through http a proper error message
Catch kafka message size error and respond accordingly:
Issue a response with `413` status code 
and the following error message:
```
{
"error": {
"code": 413,
"message": "Message size too large",
"status": "INVALID_ARGUMENT"
}
}
```
=> ARGO-499 Respond with Error when message exceeds kafka's max allowed 

main.go
The default cipher suite in the crypto/tls package contains secure
ciphers, which are compatible with centos5 without compromising the
security of the server
=> ARGO-528 Use the default cipher suite

doc/v1/docs/api_subs.md, handlers.go, handlers_test.go, subscriptions/subscription.go, subscriptions/subscription_test.go, validation.go
Subscription acknowledge request accepts a list of ackIds but only uses the ackId[0]. Instead the id with the maximum offset should be acknowledged
=> ARGO-484 When a list of ack IDs is given, take into account the max ackId

stores/mock.go, stores/mongo.go
- Refactor 'project' to 'project_uuid' reference in mongo query during ModifyPushConfig request
=> Fix mongo query during sub modify push config

stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go
Subscription delete request was failing due to using old `project` field name instead of `project_uuid`
- Refactored `project` to `project_uuid` in store methods
- Refactored `project` to `projectUUID` in store interface arguments for consistency and clarity
=> Refactor project to projectUUID references

doc/swagger/swagger.yaml, doc/v1/docs/api_projects.md, handlers.go, handlers_test.go, projects/project.go, projects/project_test.go, push/push.go, routing.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go
Implement an API Call to enable deleting an existing project. Also delete it's topics and subscriptions
_note_: to be merged following ARGO-511, ARGO-510
=> ARGO-512 API Call to delete a project

auth/auth_test.go, auth/users.go, doc/swagger/swagger.yaml, doc/v1/docs/api_projects.md, doc/v1/docs/api_users.md, handlers.go, handlers_test.go, projects/project.go, projects/project_test.go, routing.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go, stores/store_test.go
Implement API Call to enable creating new users
-----------------------------------------
Each user definition now supports a list of projects in which a user participates accompanied with a list of roles for each project. For example:
```json
{
"name": "UserX",
"token": "S3CR3T",
"email": "foo@email-foo.coml",
"projects": [
{
"project_uuid": "uuid0",
"roles": [
"admin"
]
},
{
"project_uuid": "uuid2",
"roles": [
"viewer",
"consumer"
]
}
],
"service_roles":["service_admin"]
}
```
Each user has a seperate field to hold a list of service-wide roles named `service_roles`. An example of a service wide role is `service_admin` which allows users to manage projects and other users.
=> ARGO-514 API Call to create user

auth/acl.go, auth/auth_test.go, auth/users.go, doc/v1/docs/api_users.md, handlers.go, handlers_test.go, stores/mock.go, stores/mongo.go, stores/store_test.go, subscriptions/subscription.go, subscriptions/subscription_test.go, topics/topic.go, topics/topic_test.go
=> Fix ACL issues. Transfer Topic/Sub ACL logic to auth package

auth/acl.go, auth/auth_test.go, auth/users.go, handlers.go, stores/mock.go, stores/mongo.go, stores/store_test.go
ModACL request resolved in resource not found errors (e.g. subscription not found etc)
In ACL related methods use plural names as resource type ("topics", "subscriptions") and feed directly those type to the mongodb queries when selecting approprate collections (e.g. db.topics, db.subscriptions)
=> Fix sub mod ACL issues

config.json, config/config.go, config/config.json, config/config_test.go, doc/v1/docs/api_basic.md, doc/v1/docs/projects_users.md, doc/v1/mkdocs.yml, handlers.go
- Add service token feature in configuration. Service_token can be used for initial api access to create projects and users
- Add quick start guide to docs on how to create initial users and projects
=> ARGO-518 Add Service Token

config/config.go
The code was looping over the indexes of the brIDs slice and NOT the
values.
=> Fixes ARGO-582

messages/message.go
If no new messages are available during subscription pull the response returns null instead of an empty array
```
{
"receivedMessages": null
}
```
Instead the prefered response is:
```
{
"receivedMessages": []
}
```
-[x] Refactor ReceivedMessage List in messages package
=> ARGO-564 Fix subscription:pull response null

projects/project.go, projects/project_test.go
=> ARGO-587 Display project modified_on, created_on dates in zulu format

config.json, config/config.go, config/config_test.go, doc/v1/docs/api_basic.md, doc/v1/docs/projects_users.md, handlers_test.go
Adds an extra configuration parameter: ```kafka_znode```, which defines
the Zookeeper znode used by Kafka as the parent node for the Kafka data
in Zookeeper. The default value is an empty string, which means the root
Zookeeper node (/). A value of ```/argo-messaging``` would mean that the
messaging service should search for the brokers under the the node:
```
/argo-messaging/brokers/ids
```
=> Fixes ARGO-592

handlers.go, handlers_test.go, projects/project.go, projects/project_test.go, stores/mock.go, stores/store_test.go
In project information the field created_by lists the username of the project creator. The username is stored as a string in `created_by` field, so if username changes the project will reference an invalid creator name
=> ARGO-586 Project created_by field uses user uuid as a reference

Dockerfile, Makefile, README.md, docker-compose.yml
Up to know we had only one deployment model for the ARGO Messaging
Service via the use of RPMs for CENTOS and RHEL environments. This
commit adds support for orchestrating the AMS deployment via docker.
It provides a way to deploy AMS on any Linux distribution that supports
a recent version of the docker-engine and docker-compose. It has been
tested on Ubuntu 16.04.1.
Dockerized features:
- Run unit tests
- Build linux static binary
- Get certificates via letsencrypt
- Deploy Zookeper, Kafka, MongoDB and AMS
=> Adds support for docker

auth/auth_test.go, auth/users.go, doc/swagger/swagger.yaml, doc/v1/docs/api_users.md, doc/v1/docs/projects_users.md, handlers.go, handlers_test.go, projects/project.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go, stores/store_test.go
Add the following extra fields to user information
- `created_on` : zulu timestamp
- `modified_on` : zulu timestamp
- `created_by` : username of the creator
=> ARGO-588 Add Users created_on, modified_on, created_by fields

config/config.go, config/config_test.go, doc/v1/docs/api_basic.md
Add the option to specify configuration parameters through command line. Add also `--help` message
The following parameters where added 
```
--bind-ip string          
--certificate string      
--certificate-key string  
--config-dir string        
--kafka-znode string      
--per-resource-auth        
--port string             
--service-key string       
--store-db string         
--store-host string        
--zookeeper-hosts value    
```
Parameter `config-dir` allows user to specify an alternative config directory (which is expected to include a valid config.json file)
=> ARGO-580 Add command line config parameters and help

messages/message_test.go
- Remove debug printouts from unit test (causing error to coverage report tool)
=> Remove debug printout from unit test

auth/users.go
Users list specific user request displays a json with null fields when user doesn't exist. Instead it should display the appropriate json error msg
```json
{
"error": {
"code": 404,
"message": "User does not exist",
"status": "NOT_FOUND"
}
}
```
=> ARGO-595 Fix users listing null details if user doesn't exist

handlers.go
User included in subscription's acl & with consumer role, is forbidden to pull from subscription due to bug in "subscription pull" request handler. 
Use project_uuid in acl check (instead of project name)
=> ARGO-624 Fix consumer acl bug

brokers/broker.go, brokers/kafka.go, brokers/mock.go, handlers.go, push/push.go
If (during retention) tracked offset stays behind broker's min offset, api cannot consume new messages
- Check if tracked offset is behind broker's min offset, increment it and retry
=> ARGO-628 Fix offset off bug

brokers/broker.go, brokers/kafka.go, brokers/mock.go, handlers.go, push/push.go
Msg.id generation is related to broker offset for each given message. Generated msg.id just before publishing caused an issue with small sets of duplicate ids (3-4 items) when published messages were in low time intervals (below 0.001 seconds). 
Msg.id is applied during consumption of messages. During subscription:pull handler, the read offset and the list of returned messages is reported and each message is assigned an appropriate msg.id according its position from read offset.
- Secondary fix: delay in broker.consume loop when returnImmediately is not set
=> ARGO-630 Fix msg id mapping to broker offset issue

handlers.go
When a new subscription is created it must receive the latest topic's offset. Instead it begins with offset=0. This is due to a bug with not using project_uuid correctly when asking for topic offset
Refactor method to use project_uuid when asking for a topic's max offset
=> ARGO-640 Add latest topic offset when creating a new subscription

brokers/kafka.go, handlers.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go
Subscriptions with the same name but in different projects cause a wrong datastore update during pull requests.
- Refactor UpdateSubPull method in stores package
- Update unit tests
- Minor fix in consume loop for returnImmediately if number of maxMessages is smaller than available ones
- Minor fix in request ack: If user acknowledged with ackId - 1 nothing happened and request returned 200. Now returns wrong ack id as expected
=> ARGO-646 Sub pull update fix

handlers.go, handlers_test.go, stores/mock.go
Push configuration must accept only an https push endpoint. Until now there was no check for the validity of the user's push endpoint string (if its a valid https url)
- Implement isValidHTTPS method that accepts a url string and checks if its a valid HTTPS url (uses net/url lib to check the validity and https scheme)
- Refactor handlers to call isValidHTTPS in push configuration related requests. 
- Return an appropriate error response if push endpoint url is not https
- Add unit tests, testing for invalid push configuration endpoints when handling Subscription Creation and Subscription Modify Push Configuration
=> ARGO-650 Push endpoint should be https

doc/v1/docs/api_subs.md
Updated example to api_subs documentation that lead to error to messaging. There was a comma in the post body after the ackIds. This lead to wrong parameter fot the user and 408 ack timeout to the messsaging service.
=> Updated example to api_subs documentation

doc/v1/docs/api_subs.md
This seems to be a mistake in the docs, so change the reference to deleting a topic to deleting a sub in the section on deleting subs.
=> Correct reference to sub/topic in api_subs.md

stores/mongo.go
Every subscription update operation during request handling was preceded by checking that the specific subscription already existed. If subscription was deleted during by another request during the handling of the specific request an unhandled ErrNotFound was causing a log.Fatal result in stopping argo-messaging service
Acknowledge ErrNotFound during update operations and continue without calling log.Fatal
=> ARGO-813 Handle gracefully "not found" error during datastore updates

doc/swagger/swagger.yaml, doc/v1/docs/api_topics.md, handlers.go, handlers_test.go, messages/message.go, messages/message_test.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go, stores/store_test.go, topics/topic.go
Implement metric: data volume (total bytes of messages) published to a topic
=> ARGO-779 Implement metric: data volume published to a topic

doc/swagger/swagger.yaml, doc/v1/docs/api_subs.md, handlers.go, handlers_test.go, push/push.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go, stores/store_test.go, subscriptions/subscription.go
Implement metric for data volume (total bytes of messages) consumed by a subscription
=> ARGO-780 Implement Metric: data volume consumed by subscription

doc/swagger/swagger.yaml, doc/v1/docs/api_projects.md, handlers.go, handlers_test.go, metrics/models.go, metrics/models_test.go, metrics/queries.go, routing.go, stores/mock.go, stores/mongo.go, stores/store.go
Add metric: number of topics per project/user
```
{
"metrics": [
{
"metric": "project.number_of_topics",
"metric_type": "counter",
"value_type": "int64",
"resource_type": "project",
"resource_name": "PROJECT-TEST",
"timeseries": [
{
"timestamp": "2017-06-23T04:50:02Z",
"value": 3
}
],
"description": "Counter that displays the number of topics belonging to the specific project"
}
]
}
```
With the above schema each metric can have a metric name, a metric type (for eg, counter, state values, enumerations etc), a resource name (in this specific case the project itself) and a resource type. Also a description string can notify the user about the details of the metric. API returns the latest metric value (doesn't support history of metrics yet) but the model itself supports it with the …
=> ARGO-862 Add metric: number of topics per project/user

doc/swagger/swagger.yaml, doc/v1/docs/api_projects.md, handlers.go, handlers_test.go, metrics/models.go, metrics/models_test.go, metrics/queries.go, routing.go, stores/mock.go, stores/mongo.go, stores/store.go
Add metric: number of subscriptions per project/user
```
{
"metrics": [
{
"metric": "project.number_of_topics",
"metric_type": "counter",
"value_type": "int64",
"resource_type": "project",
"resource_name": "ARGO",
"timeseries": [
{
"timestamp": "2017-06-23T05:47:13Z",
"value": 3
}
],
"description": "Counter that displays the number of topics belonging to the specific project"
},
{
"metric": "project.number_of_subscriptions",
"metric_type": "counter",
"value_type": "int64",
"resource_type": "project",
"resource_name": "ARGO",
"timeseries": [
{
"timestamp": "2017-06-23T05:47:13Z",
"value": 4
}
],
"description": "Counter that displays the number of subscriptions belonging to the specific project"
}
]
}
```
=> Subscription number

doc/swagger/swagger.yaml, doc/v1/docs/api_topics.md, handlers.go, handlers_test.go, metrics/models.go, metrics/models_test.go, metrics/queries.go, stores/mock.go, stores/mongo.go, stores/store.go
Add metric: number of subscriptions per topic
-[x] Implement GetSubscriptionsPerTopic method in datastore
-[x] Implement Number of Subscriptions per topic metric in `metrics` package
-[x] Refactor topic.number of bytes  to the new metric model
-[x] Refactor topic.number of messages to the new metric model
-[x] Refactor handler topic:metrics to support the new metrics
-[x] Update unit tests
-[x] Update documentation
=> ARGO-866 Metric: number of subscriptions per topic

doc/swagger/swagger.yaml, doc/v1/docs/api_subs.md, handlers.go, handlers_test.go, metrics/metrics_test.go, metrics/models.go, metrics/queries.go, stores/mongo.go
Add new metric: Aggreagation of topics per user for a specific project
- Add method for aggregating topics per user for a specific project (metrics package)
- Refactor project metrics request handler to use the new method
- Refactor subscription metrics to the new schema:
- - Add const descriptions for subscription metrics in metrics package
- - Add new subscription metric constructors
- - Refactor subscription metrics request handler to use the new methods 
- - Update swagger
- Update unit tests
- Update documentation
=> ARGO-863 Add metric: Aggregation of topics per user at project. 

doc/swagger/swagger.yaml, doc/v1/docs/api_metrics.md, doc/v1/mkdocs.yml, handlers.go, handlers_test.go, metrics/metrics_test.go, metrics/models.go, metrics/operational.go, routing.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go
Add operational metric: memory usage for ams nodes
=> ARGO-859 Add operational metric: memory usage for ams nodes

doc/swagger/swagger.yaml, doc/v1/docs/api_metrics.md, doc/v1/mkdocs.yml, handlers.go, handlers_test.go, metrics/metrics_test.go, metrics/models.go, metrics/operational.go, routing.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go
Add operational metric: CPU usage for ams nodes
=> ARGO-860 Add CPU Usage metric for ams service nodes

brokers/broker.go, brokers/kafka.go, brokers/mock.go, handlers.go, push/push.go
returnImmediately=true functionality during a pull operation doesn't seem to work when a previous non-returnImmediately pull operation has been requested on the specific topic.
This is due to the fact that the consume operation doesn't watch if the previous request has been canceled from the client and still waits for the timeout
Provide request context object to the broker consume loop. Break if request has been canceled
=> ARGO-925 Fix returnImmediately functionality in pull operation

brokers/kafka.go
Meta-data field publishedTime contains timestamp in AMS cluster localtime. Use UTC instead
Convert time to UTC before exporting timestamp
=> ARGO-1003 Fix publishedTime to be in UTC instead of localtime

brokers/kafka.go, config/config.go, main.go, stores/mongo.go
Refactor AMS start-up process to rely on retries while connecting to the back-end services (broker, datastore, zookeeper)
- Refactor store package to use retry to connect during init
- Refactor broker package to use retry to connect during init
- Refactor config package to use retry to connect (zookeeper) during init
=> ARGO-1216 Retry if backends are unavailable

auth/users.go, config/config.go, handlers.go, projects/project.go, routing.go, stores/mongo.go
- In any request (except create new project) if url path has a {{project_name}} reference check immediately  for project existence and if false return. (In project create call {{project_name}} reference should indeed reference a non-existent project)
Additional fixes:
- Fix utc timestamps in get projects, get users (timestamps were inserted correctly in utc  but loaded in non-utc)
- Fix query push subs (non-push subs have `push_endpoint == " "` (instead of `null`) 
- Fix logging config.per_resource_auth param value (show correct value in logging during service initialization)
=> ARGO-1359 Handle empty project_uuid references

argo-messaging.spec
Set cap cap_net_bind_service=+ep for argo-messaging binary directly in the spec file
=> ARGO-1364 Set-cap option in spec file

argo-messaging.spec
noreplace param in spec file when deploying argo-messaging.conf
=> ARGO-1365 Add config noreplace param in spec file

doc/swagger/swagger.yaml, doc/v1/docs/api_subs.md, handlers.go, handlers_test.go, routing.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go, subscriptions/subscription.go, subscriptions/subscription_test.go
Give the ability to modify the ack deadline in a subscription (time available to ack messages after pull)
- Implement handling of subscriptions:modifyAckDeadline POST request
- Update store package with ModAck method
- Update subscription package with ModAck method
- Implement SubModAck handler
- Update routing
- Update swagger
- Add unit tests
- Update mkdocs
=> ARGO-421 Modify sub's ack deadline

doc/swagger/swagger.yaml, doc/v1/docs/api_subs.md, handlers.go, handlers_test.go, routing.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go, subscriptions/subscription.go, subscriptions/subscription_test.go
add a new api call to modify the push status field of a subscription. The call is mostly to be used by the ams push server in order to update the status of a subscription in ams when various errors occur. Also updated swagger and mkdocs
**/projects/p1/subscriptions/s1:modifyPushStatus**
- Added a new handler for the respective route
- Added a new store function for updating the status field
- Since the push status field now has its own functions to take care of it, refactor any previous functions that needed extra arguments in order to take care of the push status field aswell
=> ARGO-1606 Update push status field api call

handlers.go, handlers_test.go, main.go, push/grpc/client/mock.go, routing.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go, subscriptions/subscription.go, subscriptions/subscription_test.go
Whenever the **modifyPushConfig** action is called, we check if the subscription has an active push config in order to deactivate it. If there was no prior push config active we skip this step. Next, we check if the push config in the request is activated or deactivated(null or not) in order to activate the subscription with the new values.
=> ARGO-1600 Add push server interaction on modify push config api call

auth/acl.go, auth/auth_test.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go
Add to the store interface a new append to acl method.
The mongo store implements this method by using the **$addToSet** and **$each** operators.
=> ARGO-1650 Internal function - append user(s) to topic/sub ACL

auth/acl.go, auth/auth_test.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go
Add to the store interface a new remove from acl method.
The mongo store implements this method by using the **$pullAll** operator.
=> ARGO-1651 Internal function - remove user(s) from topic/sub ACL

doc/swagger/swagger.yaml, doc/v1/docs/api_subs.md, handlers.go, handlers_test.go, routing.go, stores/store_test.go, subscriptions/subscription.go, subscriptions/subscription_test.go
Introduce a new api call that lists all subscription's linked to the respective topic. Update swagger and mkdocs aswell.
**/projects/p1/topics/t1/subscriptions**
- Add a new handler for the respective api call.
- Add a new struct to hold the sub's names as a list
- Create a wrapper function around the already existing store method, **QuerySubsByTopic**
=> ARGO-1639 API Call - List topic's subscriptions

auth/auth_test.go, auth/users.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go
AppendToUserProjects method for the store interface.
The mongo store implements this method by using the **$addToSet** operator.
We also provide a wrapper function that will be mainly used to link a subscription's project with the push worker user.
=> ARGO-1656 Internal function - append project to user's projects

auth/auth_test.go, auth/users.go, config.json, config/config.go, config/config.json, handlers.go, handlers_test.go, stores/mock.go, stores/store_test.go
Provide a new function in the auth package that attempts to retrieve the push worker user based on the provided parameters.
Also, modify the SubCreate and SubModPush handlers to use the above-mentioned function in order to take care of all the push functionality cases that might occur as they are being described in the respective jira ticket.
=>  ARGO-1661 Ams handling of push worker initialisation

auth/auth_test.go, config.json, handlers.go, handlers_test.go, stores/mock.go, stores/store_test.go
Upgrade the SubCreate and ModPushStatus handlers to link the push worker user to the sub's project and append him to the sub's acl(when creating or updating). Also, remove the push worker user from a sub's acl when turning a push subscription to pull.
=> ARGO-1657 Add/remove push worker from sub's acl and link him with sub's project

auth/users.go, doc/swagger/swagger.yaml, doc/v1/docs/api_topics.md, handlers.go, handlers_test.go, metrics/queries.go, projects/project_test.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go, topics/topic.go, topics/topic_test.go
Update the already existing methods that are used to query the topics collection to accept an extra argument, **userUUID**.
Given the route **/projects/{project}/topics**
if the user making the request is not a project or service admin and he has publisher role for the respective project, we load the topics he has access to.
=> ARGO-1631 Add ACL-based access to topics:list

auth/auth_test.go, auth/users.go, doc/swagger/swagger.yaml, doc/v1/docs/api_subs.md, handlers.go, handlers_test.go, metrics/queries.go, projects/project_test.go, push/push.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go, subscriptions/subscription.go, subscriptions/subscription_test.go
Update the already existing methods that are used to query the subscriptions collection to accept an extra argument, **userUUID**.
Given the route **/projects/{project}/subscriptions**
if the user making the request is not a project or service admin and he has consumer role for the respective project, we load the subscriptions he has access to.
=> ARGO-1632 Add ACL-based access in subscriptions:list

auth/auth_test.go, auth/users.go, handlers.go, handlers_test.go, metrics/metrics_test.go, stores/mock.go, stores/store_test.go, topics/topic_test.go
Update the **SubPull** handler to check whether or not the given subscription is push enabled.
If it is push enabled, allow only users with a service role of push_worker or service_admin to pull, otherwise return a 403 forbidden error.
=> ARGO-1669 Allow only push worker user to pull from push enabled subscription

handlers.go, handlers_test.go
Provide a new rpc call **Status** that returns the state of the service.
Also provide a wrapper around the rest of the rpc calls that prevents requests from accessing them, IF the state of the service is erroneous.
=> ARGO-1684 update status call to handle push enabled false

tools/republisher.py, tools/republisher.template.json
**Script that republishes messages that concern specific SITES**
The **republisher** provides a cli argument **-c** in order for the user to specify the location of the configuration file needed, which needs to have the following form.
{
"syslog_socket": "",
"sites": ["SITE-A", "SITE-B", "SITE-C"],
"ams_project": "",
"ams_host": "",
"ams_port": ,
"ams_token": "",
"avro_schema": "/etc/argo-messaging/metric_data.avsc",
"bulk_size": ,
"interval": ,
}
The republisher executes the following workflow:
1) consume from the **metric_data_repub** subscription up to 100 messages
2) filter thse messages to see which ones of them concern any of the predefined sites
3) republish each filtered message to a topic that has the same name as its corresponding site
4) **makes sure** that the last message …
=> ARGO-1723 Republishing of specific messages

doc/swagger/swagger.yaml, doc/v1/docs/api_subs.md, handlers.go, handlers_test.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go, stores/store_test.go, subscriptions/subscription.go, subscriptions/subscription_test.go
Add to new field to the push configuration struct, **verification_hash** and **verified**, to help the verification process of the registered push endpoint.
Modified the SubCreate and the ModSubPush handlers to take care of these new fields.
=> ARGO-1787 Add verification_hash and verified fields for push enabled subscriptions

doc/swagger/swagger.yaml, doc/v1/docs/api_subs.md, examples/flask_receive_endpoint/receiver.py, handlers.go, handlers_test.go, routing.go, subscriptions/subscription.go, subscriptions/subscription_test.go
- Add a new Http handler, **SubVerifyPushEndpoint**
- Add a new function, VerifyPushEndpoint in the subscriptions package that handles the logic behind verifying the ownership of a push endpoint
- Add a new method to the subscription struct that extracts the host:port from the registered push endpoint
- Extended the flask endpoint to provide an api call for verifying push endpoints
=> ARGO-1792 API Call - Verify Push Endpoint

auth/auth_test.go, auth/users.go, doc/swagger/swagger.yaml, doc/v1/docs/api_projects.md, doc/v1/docs/api_users.md, handlers.go, handlers_test.go, projects/project.go, routing.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go
Allow to list user members of a specific project (project_admins and service_admins allowed to do this)
Allow listing users per project. When this call is used by service_admins all user information is available. When this call is used by project admins the following user fields are ommited: `token`, `service_roles`, `created_by` as well info on roles that the user might have on other projects. 
The listing of users per projects is implemented in three api requests and supports pagination: 
- **existing one:** `/v1/users` by using and additional urlParam `project={project_name}`
This api call is available only to service admins that could list all users using pagination but now can also filter by project
- **a new one:** `v1/projects/{project_name}/members`
This api call is available to …
=> ARGO-1880 List user members of a project

brokers/mock.go, handlers.go, handlers_test.go, schemas/schema.go, schemas/schema_test.go
- Added a new fucntion to the schemas package, 
**ValidateMessages(schema Schema, msgList messages.MsgList) error {}**
that validates all the provided messages against the given schema.
The function validates checks each message for b64 encoding, valid JSON format and schema compatability.
- Updated the **TopicPublish** http handler to know invoke the ValidateMessages function whenever a topic has a declared schema.
- Small change on the mock broker to dynamically return the topic name so it can be used with all topics and not just topic1.
=> ARGO-2049 Validate message payload on topic:publish call

brokers/mock.go, doc/swagger/swagger.yaml, doc/v1/docs/api_schemas.md, handlers.go, handlers_test.go, routing.go, schemas/schema.go, schemas/schema_test.go
- Added a new http handler **SchemaLIstAll** that returns all the schemas under the provided project.
- url: **/projects/{project}/schemas**
- Utilized the already existing **schemas.Find()** function that returns all schemas if the only argument is the **project_uuid**.
=> ARGO-2068 New API Call - Retrieve all schemas under a project

argo-messaging.spec, doc/swagger/swagger.yaml, doc/v1/docs/api_version.md, doc/v1/docs/index.md, handlers.go, main.go, routing.go, version/version.go
Add version information in argo-messaging binary (in the same way as in argo-web-api https://github.com/ARGOeu/argo-web-api/pull/299)
Add version information to binary
Allow to use `/v1/version` to get version information in following format 
```
{
"release": "1.0.5",
"commit": "115745ad92cc2495c03dd91d724740ddda1a47c6",
"build_time": "2019-11-21T12:51:04Z",
"golang": "go1.11.5",
"compiler": "gc",
"os": "linux",
"architecture": "amd64"
}
```
=> ARGO-2090 Add version info in argo-messaging binary

auth/users.go, handlers.go, handlers_test.go
Prohibit duplicate project references in user profiles when creatin a user and when updating a user
- Update `CreateUser` and `UpdateUser` methods in auth package to check for duplicate project references in input structs
- Update unit tests to demonstrate new checks
=> ARGO-1984 Prohibit duplicate project references in user profiles

doc/swagger/swagger.yaml, doc/v1/docs/api_schemas.md, handlers.go, handlers_test.go, routing.go, schemas/schema.go
- Add a new API call to explicitly validate a message against a registered schema
route: (POST) **/projects/{project}/schemas/{schema}:validate**
The post body of the request should be the message it self.
e.g. { "email": "email1", "name": "n1"}
- Added a new http handler **SchemaValidateMessage** that converts the message to an internal
**messages.MsgList** in order to use the already existing **schemas.ValidateMessages**
- Updated swagger,mkdocs and tests.
=> ARGO-2086 Idea for argo-messaging: add validate action to schema resource

Jenkinsfile
This PR contains the trigger of the swagger doc generation job in case of a successful build at the devel branch.
=> DEVOPS-57 Add downstream job build at post build steps

Jenkinsfile
By adding newContainerPerStage() option we force jenkins to execute in a freshly spawned container for each stage. The container that it will be used is the one specified at the top level if there isn't specified any stage specific image.
=> DEVOPS-54 Execute each stage on different container

doc/swagger/swagger.yaml, doc/v1/docs/api_projects.md, handlers.go, handlers_test.go, routing.go
New api call that allows a project admin to add members/users to its project.
URL: /v1/projects/{{project}}/members/{{user}}:add
body: 
{
"roles": ["consumer"],
"topics": ["topic1"],
"subscriptions": ["sub1"]
}
- The user needs to exist in the AMS
- The user must not already be a user of the project
=> ARGO-2364 Allow project admin to add users to its project

auth/auth_test.go, auth/users.go, doc/swagger/swagger.yaml, doc/v1/docs/api_registrations.md, doc/v1/docs/index.md, handlers.go, handlers_test.go, routing.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go, stores/store_test.go
Added a new API Call that will allow users to register for an account in the AMS
URL: POST - /registrations
body: 
{
"name": "username-1",
"first_name": "first-name",
"last_name": "last-name",
"email": "test@example.com",
"organization": "org1",
"description": "desc1"
}
The service will also add two additional fields that will be needed by further API calls which are,
**activation_token** and **status**.
=> ARGO-2373 New API Call - User register

auth/auth_test.go, auth/users.go, doc/swagger/swagger.yaml, doc/v1/docs/api_registrations.md, handlers.go, handlers_test.go, routing.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go, stores/store_test.go
Added a new API Call that will allow a service admin to accept a user's registration.
URL: POST - /registrations/{uuid}: accept
By accepting a user's registration, the service will also create the respective user with the information provided by the registration.
The registration itself will be updated with an accepted status, and the modified_at and modified_by will contain the timestamp of the action, and the service_Admin that performed it respectively.
=> ARGO-2374 New API Call - Accept a user's registration

auth/auth_test.go, auth/users.go, doc/swagger/swagger.yaml, doc/v1/docs/api_registrations.md, handlers.go, handlers_test.go, routing.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go, stores/store_test.go
Added a new API Call that will allow a service admin to decline a user's registration.
URL: POST - /registrations/{uuid}: decline
The registration itself will be updated with an declined status, and the modified_at and modified_by will contain the timestamp of the action, and the service_Admin that performed it respectively.
=> ARGO-2375 New API Call - Decline a user's registration

auth/auth_test.go, auth/users.go, doc/swagger/swagger.yaml, doc/v1/docs/api_registrations.md, handlers.go, handlers_test.go, routing.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go, stores/store_test.go
Added a new API Call that will retrieve information for a specific registration
URL: GET - /registrations/{uuid}
Response:
{
"uuid": "ur-uuid1",
"name": "urname",
"first_name": "urfname",
"last_name": "urlname",
"organization": "urorg",
"description": "urdesc",
"email": "uremail",
"status": "pending",
"activation_token": "uratkn-1",
"registered_at": "2019-05-12T22:26:58Z",
"modified_by": "UserA",
"modified_at": "2020-05-15T22:26:58Z"
}
=> ARGO-2380 New API Call - List one registration

auth/auth_test.go, auth/users.go, doc/swagger/swagger.yaml, doc/v1/docs/api_registrations.md, handlers.go, handlers_test.go, routing.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go
Added a new API Call that will retrieve all registrations in the service
URL: GET - /registrations
available optional filters:
- status
- activation_token
- name
- email
- organization
Response: {
"user_registrations": [
{
"uuid": "ur-uuid1",
"name": "urname",
"first_name": "urfname",
"last_name": "urlname",
"organization": "urorg",
"description": "urdesc",
"email": "uremail",
"status": "pending",
"activation_token": "uratkn-1",
"registered_at": "2019-05-12T22:26:58Z",
"modified_by": "UserA",
"modified_at": "2020-05-15T22:26:58Z"
}
]
}
=> ARGO-2381 New API Call - List all registrations

auth/auth_test.go, auth/users.go, doc/swagger/swagger.yaml, doc/v1/docs/api_health.md, doc/v1/docs/api_metrics.md, doc/v1/docs/index.md, handlers.go, handlers_test.go, projects/project_test.go, push/grpc/client/client.go, push/grpc/client/client_test.go, push/grpc/client/mock.go, push/grpc/client/pushclient.go, stores/mock.go, stores/mongo.go, stores/store_test.go
Add an extra url parameter, details that will indicate whether or not ams should return the detailed status from an erroneous connection with the push server.
When accessing the details URL parameter the user should also provide an API token key that corresponds to an admin_viewer or service_admin user.
=> ARGO-2649 Extend the health API Call to include push server connectivity errors

doc/swagger/swagger.yaml, doc/v1/docs/api_topics.md, handlers/topics.go, handlers/topics_test.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go, stores/store_test.go, topics/topic.go, topics/topic_test.go
Add a new field to the topic struct, **created_on**.
The field is assigned a value whenever the create topic handler gets called.
Updated tests,docs and swagger.
=> ARGO-2705 Add extra topic field created_on

doc/swagger/swagger.yaml, doc/v1/docs/api_metrics.md, handlers/metrics.go, handlers/metrics_test.go, metrics/metrics_test.go, metrics/models.go, metrics/queries.go, projects/project.go, projects/project_test.go, routing.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go
Rename the api call **/metrics/daily-message-average** to **/metrics/va_metrics**
The new api response will now include the **users_count**, **topics_count** and **subscriptions_count** for the specified time window for the whole service(not influenced by the projects parameter).
Rearrange some functions to group them under the metrics package.
Add some new methods to the store interface.
update swagger,docs,test.
=> ARGO-2707 Create a new metrics API Call

auth/auth_test.go, handlers/users_test.go, stores/mock.go, stores/mongo.go, stores/store_test.go
The paginated users query method doesn't honor the project_uuid parameter when counting how many users exist under the specified project.It instead returns the count for the whole collection despite returning users for the specific project.
=> ARGO-2762 Projects:members user count bug

README.md, config.json, config/config.go, config/config.json, config/config_test.go, doc/swagger/swagger.yaml, doc/v1/docs/api_auth.md, doc/v1/docs/api_basic.md, doc/v1/docs/security.md, handlers/handlers.go, handlers/handlers_test.go, routing.go
Provide a new config field that can take the value of key, header or both.
the default value is key.
In the case of header, the service will look to find the appropriate access token in the x-api-key header.
In the case of key, the service will look to find the appropriate access token in the key URL parameter.
In the case of both, the service will first look to find an x-api-key token and then back off to the URL parameter in case it is empty.
=> ARGO-2767 Implement authorization header

Jenkinsfile, README.md, argo-messaging.spec, brokers/kafka.go, doc/v1/docs/api_version.md
- Use the new image epel-7-mgo1.15 inside the Jenkisfile
- small adjustments for the upgrade to go1.15 from go 1.14
=> ARGO-2899 Vulnerable GO version

Jenkinsfile
Due to a change in the Jenkinsfiles orientation this directive is not any more useful.
=> Remove downstream swagger job triggering

auth/auth_test.go, auth/users.go, doc/swagger/swagger.yaml, doc/v1/docs/api_projects.md, doc/v1/docs/api_users.md, handlers/projects.go, handlers/projects_test.go, handlers/registrations_test.go, handlers/users.go, handlers/users_test.go
Enhance the 2 users:listall and project:members API calls to now include an extra URL parameter, details that can hold a boolean value.
True: will return the full detailed view of a user, including projects, subs and topics
False(default): will return just the basic info for each user.
=> ARGO-2927 - Users:listall & project:members option for detailed view

stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store_test.go
Subs and Topics that have no users in their acl do not contain the acl field in their db document breaking the query user that uses the $in operator.
=> ARGO-2930 Sub and Topic ACL should be initialized as empty array

main.go
Allow `x-api-key` header in CORS settings
=> AM-154 Allow x-api-key header in CORS settings

.gitignore, examples/flask_receive_endpoint/receiver.py
Updates in flask receive endpoint:
=> Update receiver endpoint example. Add vscode gitignore

doc/swagger/swagger.yaml, doc/v1/docs/api_projects.md, doc/v1/docs/api_subs.md, go.mod, handlers/projects.go, handlers/subscriptions.go, handlers/subscriptions_test.go, main.go, push/grpc/client/client.go, push/grpc/client/mock.go, push/grpc/client/pushclient.go, push/sender.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go, stores/store_test.go, subscriptions/subscription.go, subscriptions/subscription_test.go
Introduced 4 new fields to the push config struct.
type, which indicates what type of push subscriptions is going to be created, http_endpoint or mattermost
mattermost_url(required), which is the  webhook_url
mattermost_username, which is the name the message will be delivered under in the channel
mattermost_channel, which is the channel where the messages will be delivered
Also changed some function definitions since the number of arguments has grown too much and readability has been reduced.
=> AM-254: ams: Enable create_sub to handle mattermost webhooks

doc/swagger/swagger.yaml, handlers/metrics.go, handlers/metrics_test.go, metrics/models.go, metrics/queries.go, routing.go, website/docs/api_advanced/api_metrics.md
Add a new api call that will allow project admins to va metrics for their projects along side operational metrics for the service.
The user also has the ability to filter which of his projects wants data for, using the url query projects paramater.
The end_date and start_date parameters of the va report are supported.
GET @ /v1/users/usageReport
=> AM-284 API Call: Per project_admin usage report

auth/auth_test.go, auth/users.go, handlers/projects.go, handlers/subscriptions.go, handlers/topics.go, handlers/users.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go, subscriptions/subscription.go, subscriptions/subscription_test.go, topics/topic.go
The error regarding 
"TLS InsecureSkipVerify may be true." is something that we cannot just remove right now as we use it for local dev and also as a fallback to debug when we encounter connection errors between ams and push server
=> AM-306 Static analysis assessment fixes

brokers/kafka.go
This reverts commit 65e8e36d0327d49f718ab1291659abe0fca7a662.
=> Revert "AM-378 returnImmediately should be honored even when there are no new messages"
