ARGOeu/argo-messaging

messages/message.go, messages/message_test.go
Messages are items that take place in pub/sub routines in messaging-API. The Message Resource implementation is based on the api spec:
```json
{
"messageId": 12,
"attributes": [
{
"key": "foo",
"value": "bar"
}
],
"data": "YmFzZTY0ZW5jb2RlZA=="
}
```
- New message package with appropriate structs (for message and attribute store)
- functions for creating new messages based on data input or from a json definition
- CRUD attribute store functions for adding,deleting,updating and getting message attributes
- GetDecoded data to return decoded payload (from base64)
- Export to Json function to produce json string representation of the Message 
- Unittests for the above
=> ARGO-320 Implement Message Resource

.travis.yml, config.json, config/config.go, config/config.json, config/config_test.go, doc/swagger/swagger.yaml, handlers.go, handlers_test.go, routing.go, subscriptions/subscription.go, subscriptions/subscription_test.go
=> ARGO-322 Implement Subscription Resource

Godeps/Godeps.json, brokers/kafka.go, brokers/kafka_test.go, brokers/mock.go, config.json, config/config.go, config/config.json, config/config_test.go, doc/swagger/swagger.yaml, handlers.go, handlers_test.go, main.go, messages/message.go, routing.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go, subscriptions/subscription.go, subscriptions/subscription_test.go, topics/topic.go, topics/topic_test.go
=> ARGO-324 Implement Subscription pull method

auth/auth_test.go, doc/swagger/swagger.yaml, handlers.go, handlers_test.go, routing.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go, topics/topic.go, topics/topic_test.go
Implement topic delete Request. 
Request must adhere to the following signature:
` DELETE /v1/projects/PROJET101/topics/TOPIC101`
- if deleleted return empty response and `CODE 200`
- if not deleted return ErrorMsg and appropriate `CODE`
=> ARGO-377 Implement Topic Delete Request

doc/swagger/swagger.yaml
=> ARGO-393 Add small description and team information

doc/swagger/swagger.yaml
Description
please review /cc @kaggis
=> Minor correction in swagger.yaml

handlers.go, main.go, routing.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go
=> ARGO-418 Mgo Connection handling optimization. Godep refs fixed. 

doc/swagger/swagger.yaml
Fixes definition in swagger doc
=> Fix swagger modifyPushConfig request definition

argo-messaging.service, argo-messaging.spec
Add systemd service definition file. Update spec
=> Add systemd service definition

argo-messaging.spec
Fix add useradd groupadd in spec file
=> Fix add useradd groupadd in spec file

Godeps/Godeps.json, config.json, config/config.go, config/config.json, config/config_test.go, doc/v1/docs/api_basic.md, handlers_test.go, main.go
Dynamic discover Kafka instances from zookeeper. 
Use of go-zookeeper library
=> ARGO-413 Dynamic discovery of kafka instances

.travis.yml, Godeps/Godeps.json, push/push.go, stores/mongo.go, subscriptions/subscription.go, topics/topic.go
During push implementation, extra placement of close session directives, conflicted with the original session handling during pull requests. This PR fixes the issue by placing session closing and session cloning in the proper places.
=> ARGO-453 Fix bug: unexpected closures of mongodb sessions

handlers_test.go, validation.go
Allow "-" dash character in topic names
=> ARGO-470 Allow dash as a valid character in topic names

brokers/broker.go, brokers/kafka.go, brokers/mock.go, handlers.go, push/sender.go
- Added lock to broker interface when consuming
- Refactored message id creation routine
=> ARGO-473 Fix api panic when multiple consuming from same topic

doc/swagger/swagger.yaml
- Fix swagger tag in modifyAccl
=> ARGO-468 Fix swagger Definition

doc/swagger/swagger.yaml, doc/v1/docs/api_errors.md, handlers.go, routing.go, subscriptions/subscription.go, topics/topic.go
=> Fix ARGO-505, ARGO-506 Check user existence before modifyACL

handlers.go, stores/mongo.go
Fix mongo interface queries during authentication handling
=> Fix Mongo interface queries during authentication

stores/mongo.go
- Fix project_uuid field reference in mongo interface when querying topics and subs
=> Fix mongo topic & sub project_uuid reference

doc/v1/docs/api_projects.md, doc/v1/mkdocs.yml
Correct json format tags and add api_projects to mkdocs file so as to generate the documentations"
=> [Documentation]: Update projects 

doc/v1/docs/api_projects.md, handlers.go, handlers_test.go, projects/project.go, projects/project_test.go, routing.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go
Implement an API Call to enable updating information on existing projects
_note_: to be merged following ARGO-510
=> ARGO-511 Api Call to update a project

doc/swagger/swagger.yaml, handlers.go, handlers_test.go
=> Fix Project Show information json response

handlers.go, projects/project.go, stores/mongo.go
=> Fix Project Delete handler

auth/auth_test.go, auth/users.go, doc/swagger/swagger.yaml, doc/v1/docs/api_projects.md, doc/v1/docs/api_users.md, handlers.go, handlers_test.go, projects/project.go, projects/project_test.go, routing.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go, stores/store_test.go
Implement Call to update user information 
Implement Call to refresh user token
=> ARGO-516 Update users

auth/auth_test.go, auth/users.go, doc/swagger/swagger.yaml, doc/v1/docs/api_users.md, handlers.go, handlers_test.go, routing.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go
Implement request to delete a user
for e.g.:
```json
{
"projects": [],
"name": "UserA",
"token": "S3CR3T1",
"email": "foo-email",
"service_roles": []
}
```
=> ARGO-517 Implement API Call to delete user

doc/v1/docs/api_users.md, doc/v1/docs/projects_users.md
Add role reference table to docs:
- auth.md 
- projects_users.md
Fix 'producer' to 'publisher' reference in docs
=> Add available user roles table in docs

handlers.go
If json body arguments are invalid during a request handling ... log out the body
=> Log out invalid json argument body during request

doc/v1/docs/api_subs.md
Fix ackDeadline parameter in subscription create request
=> doc-fix: ackDeadlineSeconds in subscription create

brokers/kafka.go
In edge cases some AMS subscriptions seemed to be stucked in the same offset not being able to continue consumption even though there were messages available for consumption in the specific topic. Pull request returned indefinitely `{"receivedMessages":[]}` without changing state.
The exact issue was reproduced locally by publishing slightly larger messages in the queue (>30kb). The consumption channel didn't handle the larger msg, with the timeout signal eventually returning an empty array of received messages. 
The issue was resolved by increasing the Fetch.Default parameter in the sarama library config structures (original default value = 32768). This should be larger than the majority of the messages published in the broker network because the library's consumer will stop consuming …
=> ARGO-796 Increase consumer default fetch size to handle larger messages

doc/swagger/swagger.yaml, doc/v1/docs/api_topics.md, handlers.go, handlers_test.go, routing.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go, stores/store_test.go, topics/topic.go, topics/topic_test.go
Implement Metric: number of messages per topic
=> ARGO-777 Implement metric: number of messages per topic

doc/v1/docs/api_projects.md, handlers.go, handlers_test.go, metrics/metrics_test.go, metrics/models.go, metrics/queries.go
Add subscriptions per user aggregation on project level
- Add Method of aggregating subscription number per user on specific project (metrics package)
- Update project metrics request handler to display the new metrics
- Update docs
=> ARGO-865 aggregation of subscriptions based on project_admin

auth/auth_test.go, auth/users.go, doc/v1/docs/api_users.md, handlers.go, handlers_test.go, routing.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go
- Refactored  user info JSON response:
```json
{
"projects": [
{
"project": "ARGO",
"roles": [
"consumer",
"publisher"
],
"topics": [
"topic1",
"topic2"
],
"subscriptions": [
"sub1",
"sub2",
"sub3"
]
}
],
"name": "UserA",
"token": "S3CR3T1",
"email": "foo-email",
"service_roles": [],
"created_on": "2009-11-10T23:00:00Z",
"modified_on": "2009-11-10T23:00:00Z"
}
```
=> ARGO-891 Implement ams request: get User info by Token. Expand user info

main.go
Define specifics to be initialized in CORS handler
=> Initialize CORS-related specifics

.gitignore, auth/auth_test.go, auth/users.go, doc/swagger/swagger.yaml, doc/v1/docs/api_users.md, handlers.go, handlers_test.go, routing.go, stores/mock.go
AMS API CALL to retrieve a user based on its UUID.
=> ARGO-1154 API CALL - Return User given a UUID

handlers.go, handlers_test.go
Fix utc time generation in utc formatted meta-data fields (created, modified)
=> ARGO-1177 Fix utc generation in utc-formatted fields

metrics/models.go
Fix metrics timestamping in UTC
=> ARGO-1282 Fix Metrics package timestamp to be utc

argo-messaging.service
Add SyslogIdentifier option in argo messaging service file.
=> ARGO-1307 Update ams service file to include a syslog identifier

tools/README.md, tools/ams-migrate.py, tools/requirements.txt
Implement a python script to automatically export AMS related topic data from kafka-backend
=> ARGO-1375 Script to export AMS kafka data

tools/README.md, tools/ams-migrate.py
- implement import functionality in ams-migrate script
- update README.md
=> ARGO-1376 Extend ams-migrate script to support import

README.md, config.json, config/config.go, config/config.json, doc/v1/docs/projects_users.md, handlers.go, main.go, push/push.go, push/sender.go
Fix nil context issue in push package
Add debug logging of delivery errors in http pushing of messages
Add flag to allow automatic handling of push subscriptions at start-up (default: false)
Fix use projectUUID instead of project name when launching a push subscription after a modPushConfig request
=> ARGO-1410 Fix nil context bug

handlers.go, main.go
Disable push functionality inside handlers.
Also add some **todos**, in order to remember what we need to revisit when we introduce a new push mechanism.
=> ARGO-1550 Disable push functionality in ams

doc/swagger/swagger.yaml, doc/v1/docs/api_subs.md, handlers.go, handlers_test.go
Update the **SubPull** handler to check if the given's subscription's topic exists.
Update swagger and mkdocs.
=> ARGO-1627 Check if the respective topic exists when pulling messages

doc/v1/docs/api_users.md, handlers.go, handlers_test.go, routing.go
Added a new handler **UserProfile** to perform user profile retrieval based on the URL parameter **key**.
**route:** **/users/profile**
updates swagger and docs aswell.
=> ARGO-1649 API Call that returns a user's profile based on the provided auth token

auth/auth_test.go, auth/users.go, handlers.go, handlers_test.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go, subscriptions/subscription.go, subscriptions/subscription_test.go
Contais both 1801 and 1802 jira tickets.
=>  ARGO-1801 Update response Verify push endpoint call

tools/README.md, tools/consumer.py
Update stream_consumer script
Add new Consumer script
=> Consumer script

brokers/kafka.go, handlers.go
…n:pull whenever a kafka error is encountered
=> ARGO-1840 Update the error response for topic:publish and subscription:pull whenever a kafka error is encountered

doc/v1/docs/api_subs.md
Add missing documentation on Subscription modify ACL as mentioned in 
issue: https://github.com/ARGOeu/argo-messaging/issues/235
=> ARGO-1883 update docs with info on modifying subscription's ACL

doc/v1/docs/index.md
Add missing section references in documentation index
=> Update doc index

Jenkinsfile
This pr includes a fix at the env variables declaration and removes the mongodb restart command at the testing stage
=> Fix environment variables

Jenkinsfile
Instead of having the script in every jenkinsfile we use the build-rpm.sh script to import it from each jenkinsfile we want
=> DEVOPS-54 Use script in packaging stage

Jenkinsfile
Change name of downstream job to be compatible with new jenkins
=> DEVOPS-77 Integrate new jenkins

Jenkinsfile
Clean up workspace at the end of every job run
=> DEVOPS-111 Add cleanWs statement at the end of the build

doc/v1/docs/api_users.md, handlers.go, handlers_test.go
Update the UserCreate API call to also accept the newly added fields of
first_name, last_name, organization and description
=> ARGO-2382 Update the UserCreate API Call to include the newly added fields

auth/auth_test.go, auth/users.go, doc/swagger/swagger.yaml, doc/v1/docs/api_users.md, handlers.go, handlers_test.go, stores/mock.go, stores/mongo.go, stores/store.go, stores/store_test.go
Update the UserUpdate API call to also accept the newly added fields of first_name, last_name, organization and description
=> ARGO-2383 Update the UserUpdate API Call to include the newly added fields

doc/swagger/swagger.yaml, doc/v1/docs/api_subs.md, handlers/subscriptions.go, handlers/subscriptions_test.go, stores/mock.go, stores/mongo.go, stores/query_models.go, stores/store.go, stores/store_test.go, subscriptions/subscription.go, subscriptions/subscription_test.go
Add a new field to the sub struct, created_on.
The field is assigned a value whenever the create sub handler gets called.
Updated tests,docs and swagger.
=> ARGO-2706 Add extra subscription field created_on

doc/v1/docs/index.md, doc/v1/docs/security.md
Added a security overview md file that describes how AMS secures different aspects of its functionality.
The document covers:
- Authentication
- Authorization
- ACL based access to resources
- Push Subscriptions Endpoints
- Push messages auth headers
- Connectivity with PUSH server
=> ARGO-2704 AMS Security - Document

README.md
Update README.md to include a few key sections that generally describe the service and how to interact with it.
=> ARGO-2453 Update README in messaging

handlers/handlers.go
Hide api key from request URL log.
=> ARGO-2920 Authentication token in request URL

Jenkinsfile
Adding a security check stage to verify that the produced binary is safe. The script checksec.py is just a wrapper for the checksec command that returns exit status >0 if there is a vulnerability
=> DEVOPS-395 Add security check

website/package-lock.json
upgrade color-string from 1.5.3 to 1.6.0
=> upgrade color-string from 1.5.3 to 1.6.0

website/package-lock.json
update prismjs rom 1.20.0 to 1.25.0 in /website
=>  Bump prismjs from 1.20.0 to 1.25.0 in /website

website/package-lock.json
Reverts ARGOeu/argo-messaging#372
=> Revert "Update package-lock.json"

website/package-lock.json
Reverts ARGOeu/argo-messaging#369
=> Revert " Bump prismjs from 1.20.0 to 1.25.0 in /website"

website/package-lock.json
Reverts ARGOeu/argo-messaging#368
=> Revert "upgrade color-string from 1.5.3 to 1.6.0"

website/docs/api_subs.md
In modifying offset section: fix incorrect `offset_config` to `offset` in parameter listing
=> Fix offset parameter in documentation

README.md, config.json, config/config.go, config/config.json, config/config_test.go, doc/swagger/swagger.yaml, doc/v1/docs/api_version.md, handlers/handlers.go, handlers/handlers_test.go, version/version.go
Do not merge before the respective ansible PRs are merged in order for the automatic deployment to take place with the new proxy_hostname value, added as well.
=> AM-172 Display hostname and distro information on ams api version call

Jenkinsfile
Add when condition on building and deploying the documentation page of the repo
=> Add when condition

website/docs/guides/guide_metrics.md, website/docs/guides/publisher.md, website/docs/guides/replaying_guide.md, website/docs/guides/subscriber-pull_guide.md, website/docs/guides/subscriber-push_guide.md, website/docs/guides/subscriber_guide.md, website/docs/howto/ams_push_worker.md, website/src/pages/index.js
- Changed local links from absolute to relevant
- Changed link for ams-register from old google form to ams-register frontend
=> Fix documentation references and links

website/docs/policies/tom.md
Cleanup formatting in TOM markdown doc
=> Fix formatting in TOM document

argo-messaging.spec, version/version.go
- Bumping gorilla handlers and context to latest versions
- AM-338 ams: Use the official mongodb client
- AM-38 Introduce MongoDB integration tests in AMS
- AM-326 ams:Introduce trace id identifier in logs
=> New Release 1.6.0

Jenkinsfile
=> Remove docs from jenkins
